# Generated by Django 4.2.4 on 2023-08-13 16:18

from django.db import migrations, models
import service.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aircompany',
            options={'ordering': ('name',), 'verbose_name_plural': 'AirCompanies'},
        ),
        migrations.AlterField(
            model_name='airport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=service.models.airport_image_file_path),
        ),
    ]
